name: CI Workflow with Unit Tests and Codecov

on:
  push:
    branches: [ "main", "object_detection_navigation" ]
  pull_request:
    branches: [ "main", "object_detection_navigation" ]
    types: [opened]
  workflow_dispatch:

jobs:
  build-run-upload:
    runs-on: ubuntu-latest       # any ubuntu that has docker
    defaults:
      run:
        shell: bash       # specify bash for use with docker container
    container:
      image: osrf/ros:humble-desktop # use ROS Humble from docker hub repository
    steps:
      # We want to use GitHub CI checkout version 3 to check out our branch
      - uses: actions/checkout@v3

      # Install some system packages
      - name: Install build packages
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo apt install -y doxygen lcov gcovr
          sudo apt install -y ros-humble-ament-cmake python3-colcon-common-extensions ros-humble-gazebo-ros-pkgs

          # Install OpenCV dependencies for headless mode
          sudo apt install -y libopencv-dev libgtk-3-dev
          sudo apt install -y libgl1-mesa-glx libxrender1 libfontconfig1

      # Set OpenCV to use headless mode
      - name: Set OpenCV to Headless Mode
        run: |
          echo "export OPENCV_HEADLESS=1" >> $GITHUB_ENV

      # Run all unit test, integration test, and generate combined coverage report
      - name: Build, run unit test, and generate coverage report
        run: |
          sudo chmod +x do-tests.bash
          ./do-tests.bash

      # Upload coverage result to CodeCov
      - name: Upload coverage result to CodeCov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: /github/home/ros2_ws/filtered_coverage.info 
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
